web1/browse/urls.py
from django.conf.urls import include, re_path

urlpatterns = [
]

web1/ge/urls.py
from django.conf.urls import re_path

from . import views
from . import search_views as sv
from . import ts_views as tsv
from . import qual_views as qv

app_name = 'ge'
urlpatterns = [
    re_path(r'^([0-9]+)/tissues/', views.tissues, name='tissues'),
    re_path(r'^(?P<ws_id>[0-9]+)/note_tissue/(?P<tissue_id>[0-9]+)/',
            views.NoteTissueView.as_view(), name='note_tissue'),
    re_path(r'^(?P<ws_id>[0-9]+)/classify/(?P<tissue_id>[0-9]+)/$',
            views.ClassifyView.as_view(), name='classify'),
    re_path(r'^(?P<ws_id>[0-9]+)/ae_search/',
            sv.AeSearchView.as_view(), name='ae_search'),
    re_path(r'^([0-9]+)/ae_list/([0-9]+)/', sv.ae_list, name='ae_list'),
    re_path(r'^(?P<ws_id>[0-9]+)/ae_bulk/(?P<ae_search_id>[0-9]+)/',
            sv.AeBulkView.as_view(), name='ae_bulk'),
    re_path(r'^(?P<ws_id>[0-9]+)/tissue_set/(?P<ts_id>[0-9]+)/',
            tsv.tissue_set, name='tissue_set'),
    re_path(r'^([0-9]+)/tissue_set/',
            tsv.tissue_set, name='tissue_set_create'),
    re_path(r'^(?P<ws_id>[0-9]+)/tissue_corr/',
            tsv.TissueCorrView.as_view(), name='tissue_corr'),
    re_path(r'^(?P<ws_id>[0-9]+)/tissue_set_analysis/',
            tsv.TissueSetAnalysisView.as_view(), name='tissue_set_analysis'),
    re_path(r'^(?P<ws_id>[0-9]+)/kt_tiss/(?P<ts_id>[0-9]+)/$',
            tsv.kt_tiss, name='kt_tiss'),
    re_path(r'^(?P<ws_id>[0-9]+)/tissue_stats/(?P<ts_id>[0-9]+)/$',
            tsv.tissue_stats, name='tissue_stats'),
    re_path(r'^(?P<ws_id>[0-9]+)/sigprot/(?P<tissue_id>[0-9]+)/',
            qv.SigProtView.as_view(), name='sigprot'),
    re_path(r'^(?P<ws_id>[0-9]+)/sig_qc/(?P<tissue_id>[0-9]+)/$',
            qv.sigQcView.as_view(), name='sig_qc'),
    re_path(r'^(?P<ws_id>[0-9]+)/ge_overlap/$', qv.ge_overlap, name='ge_overlap'),
    re_path(r'^(?P<ws_id>[0-9]+)/search_model/(?P<job_id>[0-9]+)/$' , sv.SearchModelView.as_view(), name='searchmodel'),
    ]

web1/web1/urls.py
from django.conf.urls import include, re_path

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

import browse.api as ba
import browse.views as bv
import runner.views as rv
import notes.views as nv
import flagging.views as fv
import moldata.views as mv
import django.contrib.auth.views as av

from two_factor.urls import urlpatterns as tf_urls

urlpatterns = [
    re_path(r'', include(tf_urls, namespace="two_factor")),
    re_path(r'^admin/', admin.site.urls),
    # delegations to duma sub-apps; everything listed here should also
    # be listed in the prefix_list in selenium/duma.py
    re_path(r'^cv/', include('nav.urls')),
    re_path(r'^cts/', include('ctsearch.urls')),
    re_path(r'^kts/', include('ktsearch.urls')),
    re_path(r'^pats/', include('patsearch.urls')),
    re_path(r'^drugs/', include('drugs.urls')),
    re_path(r'^consultant/', include('consultant.urls')),
    re_path(r'^mol/', include('moldata.urls')),
    re_path(r'^ge/', include('ge.urls')),
    re_path(r'^rvw/', include('rvw.urls')),
    re_path(r'^wsadmin/', include('wsadmin.urls')),
    re_path(r'^wsmgr/', include('wsmgr.urls')),
    re_path(r'^score/', include('score.urls')),
    re_path(r'^xws/', include('xws.urls')),
    re_path(r'^(?P<ws_id>[0-9]+)/annotate/(?P<wsa_id>[0-9]+)/',
            mv.AnnotateView.as_view(), name='annotate_redirect'),
    re_path(r'^jobs/', rv.jobs),
    re_path(r'^jobsum/', bv.jobsum,name='nws_jobsum'),
    re_path(r'^job_detail/', bv.job_detail),
    re_path(r'^users/', bv.users,name='nws_users'),
    re_path(r'^mem/', bv.MemView.as_view()),
    re_path(r'^s3_cache/', bv.S3CacheView.as_view(), name='s3_cache'),
    re_path(r'^coll_stats/', bv.CollStatsView.as_view(), name='coll_stats'),
    re_path(r'^etl_status/', bv.EtlStatusView.as_view(), name='etl_status'),
    re_path(r'^etl_order/', bv.EtlOrderView.as_view(), name='etl_order'),
    re_path(r'^etl_history/(?P<etl_dir>.+)/',
            bv.EtlHistoryView.as_view(), name='etl_history'),
    re_path(r'^credits/', bv.CreditsView.as_view(), name='credits'),
    re_path(r'^(?P<ws_id>[0-9]+)/users/', bv.users, name='users'),
    re_path(r'^note/(?P<note_id>[0-9]+)', nv.history, name='note_hist'),
    re_path(r'^upload/'
            , bv.UploadView.as_view(), name='upload'),
    re_path(r'^(?P<ws_id>[0-9]+)/workflow/', bv.WorkflowView.as_view(), name='workflow'),
    re_path(r'^(?P<ws_id>[0-9]+)/data_status/$' , bv.DataStatusView.as_view(), name='data_status'),
    re_path(r'^(?P<ws_id>[0-9]+)/patent_notes/$' , bv.PatentNotesView.as_view(), name='patent_notes'),
    re_path(r'^(?P<ws_id>[0-9]+)/review_notes/$' , bv.ReviewNotesView.as_view(), name='review_notes'),
    re_path(r'^(?P<ws_id>[0-9]+)/comp_evidence/$' , bv.CompEvidenceView.as_view(), name='comp_evidence_view'),
    re_path(r'^(?P<ws_id>[0-9]+)/competition/$' , bv.CompetitionView.as_view(), name='competition'),
    #re_path(r'^(?P<ws_id>[0-9]+)/test/$' , bv.test, name='test'),
    re_path(r'^(?P<ws_id>[0-9]+)/test/$' , bv.DumaTestView.as_view(), name='test'),
    #re_path(r'^(?P<ws_id>[0-9]+)/test_form/$' , bv.FormTestView.as_view(), name='test_form'),
    re_path(r'^(?P<ws_id>[0-9]+)/test_form/$' , bv.DumaFormTestView.as_view(), name='test_form'),
    re_path(r'^(?P<ws_id>[0-9]+)/faers/(?P<job_id>[0-9]+)/$' , bv.FaersView.as_view(), name='faers'),
    re_path(r'^(?P<ws_id>[0-9]+)/faers/$' , bv.FaersView.as_view(), name='faers_base'),
    re_path(r'^(?P<ws_id>[0-9]+)/faers_indi/$' , bv.FaersIndiView.as_view(), name='faers_indi'),
    re_path(r'^(?P<ws_id>[0-9]+)/faers_run_table/$' , bv.FaersRunTable.as_view(), name='faers_run_table'),
    re_path(r'^(?P<ws_id>[0-9]+)/faers_demo_view/$' , bv.FaersDemoView.as_view(), name='faers_demo'),
    re_path(r'^(?P<ws_id>[0-9]+)/plotly/$' , bv.plotly, name='plotly'),
    re_path(r'^(?P<ws_id>[0-9]+)/pca/$' , bv.PcaView.as_view(), name='pca'),
    re_path(r'^(?P<ws_id>[0-9]+)/gwas_search/$' , bv.GwasSearchView.as_view(), name='gwas_search'),
    re_path(r'^(?P<ws_id>[0-9]+)/gwas_qc/$' , bv.GwasQcView.as_view(), name='gwas_qc'),
    re_path(r'^(?P<ws_id>[0-9]+)/flagset/$' , fv.FlagSetView.as_view(), name='flagset'),
    re_path(r'^(?P<ws_id>[0-9]+)/drugset/$', bv.DrugSetView.as_view(), name='drugset'),
    re_path(r'^(?P<ws_id>[0-9]+)/clust_screen/',
            bv.ClustScreenView.as_view(),
            name='clust_screen',
            ),
    re_path(r'^(?P<ws_id>[0-9]+)/pathways/', bv.PathwaysView.as_view(), name='pathways'),
    re_path(r'^(?P<ws_id>[0-9]+)/proteinscores/', bv.ProteinScoreView.as_view(), name='protein_scores'),
    re_path(r'^(?P<ws_id>[0-9]+)/proteinnetwork/', bv.ProteinNetworkView.as_view(), name='protein_network'),
    re_path(r'^pathway_network/', bv.PathwayNetworkView.as_view(), name='pathway_network'),
    re_path(r'^(?P<ws_id>[0-9]+)/protein/(?P<prot_id>[A-Z0-9-]+)/',
            bv.ProteinView.as_view(),
            name='protein',
            ),
    re_path(r'^(?P<ws_id>[0-9]+)/prot_detail/(?P<prot_id>[A-Z0-9-]+)/'
            , bv.ProtDetailView.as_view(), name='prot_detail'),
    re_path(r'^(?P<ws_id>[0-9]+)/prot_search/$'
            , bv.prot_search, name='prot_search'),
    re_path(r'^(?P<ws_id>[0-9]+)/target_data/'
            , bv.TargetDataView.as_view(), name='target_data'),
    re_path(r'^(?P<ws_id>[0-9]+)/wf_diag/'
            , bv.WfDiagView.as_view(), name='wf_diag'),
    re_path(r'^(?P<ws_id>[0-9]+)/ws_vdefaults/'
            , bv.WorkspaceVersionDefaultsView.as_view(), name='ws_vdefaults'),
    re_path(r'^vdefaults/'
            , bv.WorkspaceVersionDefaultsView.as_view(), name='vdefaults'),
    re_path(r'^(?P<ws_id>[0-9]+)/jobsum/', bv.jobsum, name='jobsum'),
    re_path(r'^(?P<ws_id>[0-9]+)/job_detail/', bv.job_detail, name='job_detail'),
    re_path(r'^(?P<ws_id>[0-9]+)/jobs/', bv.jobs, name='jobs'),
    re_path(r'^$', bv.index, name='index'),
    re_path(r'^logout/$', av.LogoutView.as_view(), {'next_page': '/account/login/'}, name='mysite_logout'),
    re_path(r'^pwchange/', bv.PasswordChangeView.as_view(success_url='/'), name='pwchange'),
    re_path(r'^publish/(?P<path>.+)', bv.publish),
    re_path(r'^pstatic/(?P<path>.+)', bv.protected_static),
    re_path(r'^api/prot_search/$', ba.prot_search, name='prot_search_api'),
    re_path(r'^api/global_data_prot_search/$', ba.global_data_prot_search, name='global_data_prot_search_api'),
    re_path(r'^api/uniprot/(?P<uniprot>.+)/$', ba.uniprot_lookup, name='uniprot_lookup_api'),
    re_path(r'^api/wsa/(?P<wsa_id>.+)/$', ba.wsa_lookup, name='wsa_lookup_api'),
    re_path(r'^api/list_workspaces/$', ba.list_workspaces, name='list_workspaces_api'),
    re_path(r'^api/list_jobs/$', ba.list_jobs, name='list_jobs_api'),
    re_path(r'^api/ws_molsets/(?P<ws_id>.+)/$', ba.ws_molsets, name='ws_molsets_api'),
    re_path(r'^api/ws_protsets/(?P<ws_id>.+)/$', ba.ws_protsets, name='ws_protsets_api'),
    re_path(r'^api/molset/(?P<ws_id>.+)/(?P<molset_id>.+)/$', ba.molset, name='molset_api'),
    re_path(r'^api/protset/(?P<ws_id>.+)/(?P<protset_id>.+)/$', ba.protset, name='protset_api'),
    re_path(r'^api/search_drugs/(?P<name>.+)/$', ba.search_drugs, name='search_drugs_api'),
    re_path(r'^api/search_wsas/(?P<ws_id>.+)/(?P<name>.+)/$', ba.search_wsas, name='search_wsas_api'),
    re_path(r'^api/fetch_scores/(?P<ws_id>.+)/(?P<job_id>.+)/$', ba.fetch_scores, name='fetch_scores_api'),
    re_path(r'^api/indirect_targets/(?P<target_list>.+)/$', ba.indirect_targets, name='indirect_targets_api'),
    re_path(r'^api/pathway_data/$', ba.pathway_data, name='pathway_data_api'),
    re_path(r'^api/validate_score_json/$', ba.validate_score_json, name='validate_score_json_api'),
    re_path(r'^(?P<ws_id>[0-9]+)/ws_hits/$', bv.WsHitsView.as_view(), name='ws_hits'),
    re_path(r'^hits/$', bv.HitsView.as_view(), name='hits'),
    re_path(r'^selectabilitymodel/(?P<job_id>[0-9]+)/$' , bv.SelectabilityModelView.as_view(), name='selectabilitymodel'),
    re_path(r'^retrospective/$', bv.RetrospectiveView.as_view(), name='retrospective'),
    re_path(r'^suitability/$', bv.SuitabilityView.as_view(), name='suitability'),
    re_path(r'^selectabilityfeatureplot/$', bv.SelectabilityFeaturePlot.as_view(), name='selectabilityfeatureplot'),
    re_path(r'^metricscatterplot/$', bv.MetricScatterPlot.as_view(), name='metricscatterplot'),
    re_path(r'^xws_score_plot/$', bv.XwsScorePlots.as_view(), name='xws_score_plot'),
    re_path(r'^dashboard/$', bv.DashboardView.as_view(), name='dashboard'),
    re_path(r'^(?P<ws_id>[0-9]+)/protset_view/$',
            bv.ProtsetView.as_view(),
            name='protset_view',
            )
]

from django.conf import settings
if False and settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web1/wsmgr/urls.py
from django.conf.urls import re_path

from . import views

# XXX Eventually, all views labeled ws_admin, ds_ps, and qc in the output from
# XXX experiments/view_dir could move here.

app_name = 'wsmgr'
urlpatterns = [
    re_path(r'create_ws/',
            views.CreateWsView.as_view(), name='create_ws'),
    re_path(r'^(?P<ws_id>[0-9]+)/copy_ws/',
            views.CopyWsView.as_view(), name='copy_ws'),
    re_path(r'^(?P<ws_id>[0-9]+)/imphist/',
            views.ImportHistoryView.as_view(), name='imphist'),
    ]

web1/templates/browse/_drug_props_section.html
{% extends "collapse_section.html" %}
{% load browse_tags %}
{% block section_label %}Drug Properties{% endblock %}
{% block section_body %}
<form method="post">
	{% csrf_token %}
	<button type="submit" name='prop_refresh_btn' class="btn btn-primary">
		Update from master
	</button>
</form>
<br>
<table class="table">
<tr>
	<th> Property Name </th>
	<th> Property Type </th>
	<th> Multi-value </th>
	<th> Record Count </th>
</tr>
{% for prop in props %}
	<tr>
		<td> {{ prop.name }} </td>
		<td> {{ prop.prop_type_name }} </td>
		<td> {{ prop.multival }} </td>
		<td> {{ prop.rec_count }} </td>
	</tr>
{% endfor %}
</table>
{% endblock %}

web1/templates/browse/_gwas_note_icons.html
{% load navtools %}
{% load browse_tags %}
{% if gwds.note %}
	{% note_icon gwds.get_note_text %}
{% endif %}
<a href="{% view_url edit=gwds.make_key %}">
	{% glyph_icon 'pencil' %}
</a>

web1/templates/browse/_job_buttons.html
{% if level_status.1 %}
	<td>
	<form action="" method="post">
	{% csrf_token %}
	<input type='submit' name="make_{{ level }}" value='Update'/>
	</form>
	</td>
{% endif %}
{% if level_status.2 %}
	<td>
	<form action="" method="post">
	{% csrf_token %}
	<input type='submit' name="force_{{ level }}" value='Redo all'/>
	</form>
	</td>
{% endif %}

web1/templates/browse/_prot_safety_section.html
{% extends "collapse_section.html" %}
{% load navtools %}
{% block section_label %}Safety Data{% endblock %}
{% block section_body %}
<style>
</style>
	<h2>Safety Data</h2>
    <hr>
    <table id='safety_table' class='table'>
    </table>
    <script>
        {
        const columns = {{ safety_data.headers_data | safe }};
        const table = $('#safety_table').DataTable({
            data: {{ safety_data.rows_data | safe }},
            columns: columns,
        });
        }
    </script>
{% endblock %}

web1/templates/browse/_prot_score_section.html
{% extends "collapse_section.html" %}
{% load navtools %}
{% load process %}
{% block section_label %}Scores{% endblock %}
{% block section_body %}
	<h2>Scores</h2>
	<table class="table">
	<tr>
		<th>Score type</th>
		<th >Job</th>
		<th style="text-align:right">Score</th>
		<th style="text-align:right">Maximum score</th>
		<th style="text-align:right">Higher</th>
		<th style="text-align:right">Tied</th>
		<th style="text-align:right">Lower</th>
	</tr>
	{% for r in scores %}
		<tr>
		<td>{{ r.0 }}</td>
		<td>
			{% if r.1 %}
				{% job_summary r.1 %}
			{% endif %}
		</td>
		{{ r.2 }}
		{{ r.3 }}
		{{ r.4 }}
		{{ r.5 }}
		{{ r.6 }}
		</tr>
	{% endfor %}
    </table>
{% endblock %}

web1/templates/browse/_retro_plot.html
{% load browse_tags %}
{% if plot_form %}
<form method='POST'>
{% csrf_token %}
{{ plot_form.as_p }}
<button type='submit' name='{{plot_form_btn.0}}_btn'>{{ plot_form_btn.1 }}</button>
</form>

{% endif %}
<div
	id="{{ div_id }}"
	style="float:left; height: {{ src.height }}px; width: {{ src.width }}px;"
	class="plotly-graph-div">
</div>

<script type="text/javascript">
Plotly.newPlot("{{ div_id }}",{{ src.data_json }},{{ src.layout_json }},{{ src.config_json }});
{% if src.handles_click %}
    document.getElementById('{{ div_id }}').on('plotly_click', function(data){
        var idLookup = {{ src.id_lookup }};
        var wsId = {{ ws.id }};
		{{ src.click_handler }}
		});
{% endif %}
</script>

{% if plot_table %}
<table id="{{ div_id }}_table" class='table table-condensed table-hover'>
</table>
    <script src='/static/js/retro_datatable.js'></script>
    <script>
        fromPlotData($('#{{div_id}}_table'), {{ src.data_json }}, {{decimal_places}});
    </script>

{% endif %}


{% if extra_table %}
<hr/>
<h3>{{ extra_table_title }}</h3>
<table id="{{ div_id }}_extra_table" class='table table-condensed table-hover'>
</table>
    <script>
        fromArray($('#{{div_id}}_extra_table'), {{ extra_table | safe_json }}, {{extra_table_header | safe_json}});
    </script>
        
{% endif %}

web1/templates/browse/clust_screen.html
{% extends 'base.html' %}
{% load browse_tags %}
{% block headline %}
    Bulk Pre-screen
{% endblock headline %}
{% block header_right %}
{% if view.prescreen %}
<a href="{{ view.prescreen_url }}">Return to pre-screening</a>
{% endif %}
{% endblock header_right %}
{% block body %}
    <form method="post">
		{% if selection_form.fields %}
			{% csrf_token %}
			{{ reclassify_form.as_p }}
			<input type="submit" name='reclassify_btn'
					value="Reclassify as inactive"/>
			{% bulk_update_links 'sel_' %}
        {% else %}
			All members of cluster are classified
        {% endif %}
		<table class="table">
			<tr>
			{% for header_html in table.headers %}
				{{ header_html }}
			{% endfor %}
			</tr>
			{% for row in table.rows %}
			<tr>
				{% for cell_html in row %}
					{{ cell_html }}
				{% endfor %}
			</tr>
			{% endfor %}
		</table>
	</form>
{% endblock body %}

web1/templates/browse/credits.html
{% extends 'base.html' %}
{% load browse_tags %}

{% block headline %}
    Credits
{% endblock headline %}
{% block header_left %}
{% endblock header_left %}
{% block header_right %}
{% endblock header_right %}
{% block body %}
    <h3>Duma gratefully acknowledges use of the following databases:</h3>
    {% for credit in db_credits %}
        {% if credit.author %}
            {{ credit.author }}:
        {% endif %}
        <b><cite>{{ credit.title }}</cite>.</b>
        {{ credit.ref }}
        {% if credit.link %}
            <a href="{{ credit.link }}" target="_blank">
			{% glyph_icon 'new-window' %}
            </a>
        {% endif %}
        <hr>
    {% endfor %}
{% endblock body %}

web1/templates/browse/etl_status.html
{% extends 'base.html' %}
{% load browse_tags %}

{% block headline %}
    ETL Status
{% endblock headline %}
{% block header_left %}
{% endblock header_left %}
{% block header_right %}
<a href="{% url 'etl_order' %}">Order of updates</a>
{% endblock header_right %}
{% block body %}
{% include "_table.html" %}
{% endblock body %}

web1/templates/browse/index.html
{% extends 'base.html' %}
{% load navtools %}

{% block headline %}
Workspace Index
{% endblock %}
{% block header_left %}
    {% if show_all %}
        Showing all workspaces - 
        <a href="{% url_add_query all=0 %}">See only active workspaces</a>
    {% else %}
        Showing active workspaces - 
        <a href="{% url_add_query all=1 %}">See all workspaces</a>
    {% endif %}
{% endblock %}
{% block header_right %}
    {% if show_create_link %}
        <a href="{% url "wsmgr:create_ws" %}">Create a new workspace</a>
    {% endif %}
{% endblock %}
{% block body %}
    {% include "_datatables_load.html" %}
    <p>
	<table class="table table-condensed">
        <thead>
		<tr>
			<th>Workspace</th>
            <th>Completion</h>
			<th>Prediction Stage</th>
			<th>Latest Review Date</th>
            <th>Creation Date</th>
            <th>Data Update Date</th>
			<th>Hits</th>
			<th>Notes</th>
		</tr>
        </thead>
        <tbody>
		{% for ws in workspaces %}
			<tr>
				<td>{{ ws.link }}</td>
                <td data-order='{{ws.completion_frac}}' style='position:relative'>
                    <span
                    style='
                        background:linear-gradient(to right, #395, #395 {{ws.completion}}, #aaa {{ws.completion}});
                        width: 100px;
                        display: inline-block;
                        border: 1px solid #555;
                        color: white;
                        text-align: center;
                        border-radius: 4px;
                        '
                    >
                        {{ ws.completion }}
                    </span>
                </td>
                <td data-order='{{ws.stage_num}}'>{{ ws.stage }}</td>
                <td>{{ ws.review_date }}</td>
                <td>{{ ws.created }}</td>
                <td>{{ ws.data_update_date }}</td>
                <td>{{ ws.hits }}</td>
                <td>{{ ws.ref.get_disease_note_text|urlizetrunc:10 }}</td>
			</tr>
		{% endfor %}
        </tbody>
	</table>
    <script>
        $("table").DataTable({
            paging: false,
            order: [[3, 'desc']],
        });
    </script>
{% endblock body %}

web1/templates/browse/mem.html
{% extends 'base.html' %}

{% block headline %}
	Memory Usage
{% endblock headline %}
{% block header_right %}
{% endblock header_right %}
{% block body %}
    {% include "_table.html" with table=table %}
{% endblock body %}

web1/templates/browse/pathway_network_view.html
{% extends 'base.html' %}

{% block headline %}
    Pathway Network
{% endblock headline %}
{% block javascript %}
    {% include "_datatables_load.html" %}
{% endblock javascript %}
{% block header_left %}
{% endblock header_left %}
{% block body %}
<style>
.hover-text {
    visibility: hidden;
    background-color: #fafaff;
    border: 1px solid black;
    border-radius: 3px;
    position: absolute;
    text-align: left;
    padding: 0.75rem;
    font-size: 100%;
    z-index: 1;
    min-width: 100px;
    white-space: nowrap;
}
.hoverable {
    position: relative;
}

.hoverable:hover .hover-text {
    visibility: visible;
}

.hier-link {
    background-color: #f3f4f0;
    border: 1px solid #dde;
    padding: 0.2rem;
    margin: 0.1rem;
    border-radius: 3px;
    cursor: pointer;
    white-space: nowrap;
}
.hier-nonlink {
    white-space: nowrap;
    font-size: 90%;
}

.pathway-summary {
    padding: 1rem;
}

.tree-toggle {
    color: #aaa;
    margin-right: 0.5rem;
}

.info-hover {
    font-size: 95%;
    color: black;
}

.score-table-panel {
    box-shadow: 1px 1px 3px 0px rgba(0,0,0,1.0);
    padding: 1rem;
    margin-bottom: 2rem;
    border-radius: 0.5rem;
    overflow-x: auto;
}

#PathwayScoreTable td:nth-child(1) a{
    cursor: pointer;
}


</style>
    <div id='react'></div>


    <script src='/publish/js/main.js'></script>
    <script>
        drawPathwayTree(document.getElementById('react'));
    </script>

{% endblock body %}

web1/templates/browse/protein_network_view.html
{% extends 'base.html' %}

{% block headline %}
    Protein Network
{% endblock headline %}
{% block javascript %}
{% endblock javascript %}
{% block header_left %}
<form method='post'>
    {{ calc_form.as_p }}
    {% csrf_token %}
    <button name='calc_btn'>Calc</button>
</form>
{% endblock header_left %}
{% block body %}
	<div style="box-shadow:2px 2px 8px 1px rgba(100, 100, 100, 0.3);">
        <div id="cy" style="width:100%; height:900px;"> </div>
    </div>
    {% include "_cytoscape_load.html" %}
    <script src="/static/js/protein_network.js"></script>
    <script>
        setupNetwork({
            wsId: {{ws.id}},
            ktProts: [],
        });
        addToNetwork({{startProts}}, 1);
    </script>
{% endblock body %}

web1/templates/browse/protein_score_view.html
{% extends 'base.html' %}
{% load browse_tags %}

{% block headline %}
	Protein Scores
{% endblock headline %}
{% block javascript %}
    {% include "_plotly_load.html" %}
    {% include "_datatables_load.html" %}
    {% include "_cytoscape_load.html" %}
    {% include "_plotly_div.html" %}
{% endblock javascript %}
{% block header_left %}
    <form method="post">
        {% csrf_token %}
        {{ calc_form.as_p }}
        <input type="submit" name='calc_btn' value="Calculate"/>
    </form>
{% endblock header_left %}
{% block body %}
<style>
    tag {
        border: 1px solid #aaa;
        font-size: 80%;
        margin-right: 0.2rem;
        padding: 0.2rem;
        border-radius: 3px;
        background-color: #f1f9ff;
        white-space: nowrap;

    }
</style>
    {% for title, name in sections %}
        {% with section_name=name section_label=title content_url=url|add:"&plot="|add:name %}
            {% include '_deferred_section.html' %}
        {% endwith %}
    {% endfor %}
{% endblock body %}