web1/ge/urls.py
from django.conf.urls import re_path

from . import views
from . import search_views as sv
from . import ts_views as tsv
from . import qual_views as qv

app_name = 'ge'
urlpatterns = [
    re_path(r'^([0-9]+)/tissues/', views.tissues, name='tissues'),
    re_path(r'^(?P<ws_id>[0-9]+)/note_tissue/(?P<tissue_id>[0-9]+)/',
            views.NoteTissueView.as_view(), name='note_tissue'),
    re_path(r'^(?P<ws_id>[0-9]+)/classify/(?P<tissue_id>[0-9]+)/$',
            views.ClassifyView.as_view(), name='classify'),
    re_path(r'^(?P<ws_id>[0-9]+)/ae_search/',
            sv.AeSearchView.as_view(), name='ae_search'),
    re_path(r'^([0-9]+)/ae_list/([0-9]+)/', sv.ae_list, name='ae_list'),
    re_path(r'^(?P<ws_id>[0-9]+)/ae_bulk/(?P<ae_search_id>[0-9]+)/',
            sv.AeBulkView.as_view(), name='ae_bulk'),
    re_path(r'^(?P<ws_id>[0-9]+)/tissue_set/(?P<ts_id>[0-9]+)/',
            tsv.tissue_set, name='tissue_set'),
    re_path(r'^([0-9]+)/tissue_set/',
            tsv.tissue_set, name='tissue_set_create'),
    re_path(r'^(?P<ws_id>[0-9]+)/tissue_corr/',
            tsv.TissueCorrView.as_view(), name='tissue_corr'),
    re_path(r'^(?P<ws_id>[0-9]+)/tissue_set_analysis/',
            tsv.TissueSetAnalysisView.as_view(), name='tissue_set_analysis'),
    re_path(r'^(?P<ws_id>[0-9]+)/kt_tiss/(?P<ts_id>[0-9]+)/$',
            tsv.kt_tiss, name='kt_tiss'),
    re_path(r'^(?P<ws_id>[0-9]+)/tissue_stats/(?P<ts_id>[0-9]+)/$',
            tsv.tissue_stats, name='tissue_stats'),
    re_path(r'^(?P<ws_id>[0-9]+)/sigprot/(?P<tissue_id>[0-9]+)/',
            qv.SigProtView.as_view(), name='sigprot'),
    re_path(r'^(?P<ws_id>[0-9]+)/sig_qc/(?P<tissue_id>[0-9]+)/$',
            qv.sigQcView.as_view(), name='sig_qc'),
    re_path(r'^(?P<ws_id>[0-9]+)/ge_overlap/$', qv.ge_overlap, name='ge_overlap'),
    re_path(r'^(?P<ws_id>[0-9]+)/search_model/(?P<job_id>[0-9]+)/$' , sv.SearchModelView.as_view(), name='searchmodel'),
    ]

web1/moldata/urls.py
from django.conf.urls import re_path

from . import views,imp_views

app_name = 'moldata'
urlpatterns = [
    re_path(r'^(?P<ws_id>[0-9]+)/annotate/(?P<wsa_id>[0-9]+)/',
            views.AnnotateView.as_view(), name='annotate'),
    re_path(r'^(?P<ws_id>[0-9]+)/drug_run_detail/(?P<wsa_id>[0-9]+)/',
            views.DrugRunDetailView.as_view(), name='drug_run_detail'),
    re_path(r'^(?P<ws_id>[0-9]+)/drugcmp/',
            views.DrugCmpView.as_view(), name='drugcmp'),
    re_path(r'^(?P<ws_id>[0-9]+)/molcmp/',
            views.MolCmpView.as_view(), name='molcmp'),
    re_path(r'^(?P<ws_id>[0-9]+)/assays/(?P<wsa_id>[0-9]+)/',
            views.AssaysView.as_view(), name='assays'),
    re_path(r'^(?P<ws_id>[0-9]+)/noneff_assays/(?P<wsa_id>[0-9]+)/',
            views.NoneffAssaysView.as_view(), name='noneff_assays'),
    re_path(r'^(?P<ws_id>[0-9]+)/patent_detail/(?P<wsa_id>[0-9]+)/',
            views.PatentDetailView.as_view(), name='patent_detail'),
    re_path(r'^(?P<ws_id>[0-9]+)/dispositionaudit/(?P<wsa_id>[0-9]+)/',
            views.DispositionAuditView.as_view(), name='dispositionaudit'),
    re_path(r'^(?P<ws_id>[0-9]+)/trgimp/(?P<wsa_id>[0-9]+)/',
            imp_views.TrgImpView.as_view(), name='trgimp'),
    re_path(r'^(?P<ws_id>[0-9]+)/scrimp/(?P<wsa_id>[0-9]+)/',
            imp_views.ScrImpView.as_view(), name='scrimp'),
    re_path(r'^(?P<ws_id>[0-9]+)/trg_scr_imp/(?P<wsa_id>[0-9]+)/',
            imp_views.TrgScrImpView.as_view(), name='trg_scr_imp'),
    re_path(r'^(?P<ws_id>[0-9]+)/ind_trg_imp/(?P<wsa_id>[0-9]+)/',
            imp_views.IndTrgImpView.as_view(), name='ind_trg_imp'),
    re_path(r'^(?P<ws_id>[0-9]+)/hit_selection/',
            views.HitSelectionView.as_view(), name='hit_selection'),
    re_path(r'^(?P<ws_id>[0-9]+)/hit_selection_report/',
            views.HitSelectionReportView.as_view(), name='hit_selection_report'),
    ]

web1/web1/urls.py
from django.conf.urls import include, re_path

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

import browse.api as ba
import browse.views as bv
import runner.views as rv
import notes.views as nv
import flagging.views as fv
import moldata.views as mv
import django.contrib.auth.views as av

from two_factor.urls import urlpatterns as tf_urls

urlpatterns = [
    re_path(r'', include(tf_urls, namespace="two_factor")),
    re_path(r'^admin/', admin.site.urls),
    # delegations to duma sub-apps; everything listed here should also
    # be listed in the prefix_list in selenium/duma.py
    re_path(r'^cv/', include('nav.urls')),
    re_path(r'^cts/', include('ctsearch.urls')),
    re_path(r'^kts/', include('ktsearch.urls')),
    re_path(r'^pats/', include('patsearch.urls')),
    re_path(r'^drugs/', include('drugs.urls')),
    re_path(r'^consultant/', include('consultant.urls')),
    re_path(r'^mol/', include('moldata.urls')),
    re_path(r'^ge/', include('ge.urls')),
    re_path(r'^rvw/', include('rvw.urls')),
    re_path(r'^wsadmin/', include('wsadmin.urls')),
    re_path(r'^wsmgr/', include('wsmgr.urls')),
    re_path(r'^score/', include('score.urls')),
    re_path(r'^xws/', include('xws.urls')),
    re_path(r'^(?P<ws_id>[0-9]+)/annotate/(?P<wsa_id>[0-9]+)/',
            mv.AnnotateView.as_view(), name='annotate_redirect'),
    re_path(r'^jobs/', rv.jobs),
    re_path(r'^jobsum/', bv.jobsum,name='nws_jobsum'),
    re_path(r'^job_detail/', bv.job_detail),
    re_path(r'^users/', bv.users,name='nws_users'),
    re_path(r'^mem/', bv.MemView.as_view()),
    re_path(r'^s3_cache/', bv.S3CacheView.as_view(), name='s3_cache'),
    re_path(r'^coll_stats/', bv.CollStatsView.as_view(), name='coll_stats'),
    re_path(r'^etl_status/', bv.EtlStatusView.as_view(), name='etl_status'),
    re_path(r'^etl_order/', bv.EtlOrderView.as_view(), name='etl_order'),
    re_path(r'^etl_history/(?P<etl_dir>.+)/',
            bv.EtlHistoryView.as_view(), name='etl_history'),
    re_path(r'^credits/', bv.CreditsView.as_view(), name='credits'),
    re_path(r'^(?P<ws_id>[0-9]+)/users/', bv.users, name='users'),
    re_path(r'^note/(?P<note_id>[0-9]+)', nv.history, name='note_hist'),
    re_path(r'^upload/'
            , bv.UploadView.as_view(), name='upload'),
    re_path(r'^(?P<ws_id>[0-9]+)/workflow/', bv.WorkflowView.as_view(), name='workflow'),
    re_path(r'^(?P<ws_id>[0-9]+)/data_status/$' , bv.DataStatusView.as_view(), name='data_status'),
    re_path(r'^(?P<ws_id>[0-9]+)/patent_notes/$' , bv.PatentNotesView.as_view(), name='patent_notes'),
    re_path(r'^(?P<ws_id>[0-9]+)/review_notes/$' , bv.ReviewNotesView.as_view(), name='review_notes'),
    re_path(r'^(?P<ws_id>[0-9]+)/comp_evidence/$' , bv.CompEvidenceView.as_view(), name='comp_evidence_view'),
    re_path(r'^(?P<ws_id>[0-9]+)/competition/$' , bv.CompetitionView.as_view(), name='competition'),
    #re_path(r'^(?P<ws_id>[0-9]+)/test/$' , bv.test, name='test'),
    re_path(r'^(?P<ws_id>[0-9]+)/test/$' , bv.DumaTestView.as_view(), name='test'),
    #re_path(r'^(?P<ws_id>[0-9]+)/test_form/$' , bv.FormTestView.as_view(), name='test_form'),
    re_path(r'^(?P<ws_id>[0-9]+)/test_form/$' , bv.DumaFormTestView.as_view(), name='test_form'),
    re_path(r'^(?P<ws_id>[0-9]+)/faers/(?P<job_id>[0-9]+)/$' , bv.FaersView.as_view(), name='faers'),
    re_path(r'^(?P<ws_id>[0-9]+)/faers/$' , bv.FaersView.as_view(), name='faers_base'),
    re_path(r'^(?P<ws_id>[0-9]+)/faers_indi/$' , bv.FaersIndiView.as_view(), name='faers_indi'),
    re_path(r'^(?P<ws_id>[0-9]+)/faers_run_table/$' , bv.FaersRunTable.as_view(), name='faers_run_table'),
    re_path(r'^(?P<ws_id>[0-9]+)/faers_demo_view/$' , bv.FaersDemoView.as_view(), name='faers_demo'),
    re_path(r'^(?P<ws_id>[0-9]+)/plotly/$' , bv.plotly, name='plotly'),
    re_path(r'^(?P<ws_id>[0-9]+)/pca/$' , bv.PcaView.as_view(), name='pca'),
    re_path(r'^(?P<ws_id>[0-9]+)/gwas_search/$' , bv.GwasSearchView.as_view(), name='gwas_search'),
    re_path(r'^(?P<ws_id>[0-9]+)/gwas_qc/$' , bv.GwasQcView.as_view(), name='gwas_qc'),
    re_path(r'^(?P<ws_id>[0-9]+)/flagset/$' , fv.FlagSetView.as_view(), name='flagset'),
    re_path(r'^(?P<ws_id>[0-9]+)/drugset/$', bv.DrugSetView.as_view(), name='drugset'),
    re_path(r'^(?P<ws_id>[0-9]+)/clust_screen/',
            bv.ClustScreenView.as_view(),
            name='clust_screen',
            ),
    re_path(r'^(?P<ws_id>[0-9]+)/pathways/', bv.PathwaysView.as_view(), name='pathways'),
    re_path(r'^(?P<ws_id>[0-9]+)/proteinscores/', bv.ProteinScoreView.as_view(), name='protein_scores'),
    re_path(r'^(?P<ws_id>[0-9]+)/proteinnetwork/', bv.ProteinNetworkView.as_view(), name='protein_network'),
    re_path(r'^pathway_network/', bv.PathwayNetworkView.as_view(), name='pathway_network'),
    re_path(r'^(?P<ws_id>[0-9]+)/protein/(?P<prot_id>[A-Z0-9-]+)/',
            bv.ProteinView.as_view(),
            name='protein',
            ),
    re_path(r'^(?P<ws_id>[0-9]+)/prot_detail/(?P<prot_id>[A-Z0-9-]+)/'
            , bv.ProtDetailView.as_view(), name='prot_detail'),
    re_path(r'^(?P<ws_id>[0-9]+)/prot_search/$'
            , bv.prot_search, name='prot_search'),
    re_path(r'^(?P<ws_id>[0-9]+)/target_data/'
            , bv.TargetDataView.as_view(), name='target_data'),
    re_path(r'^(?P<ws_id>[0-9]+)/wf_diag/'
            , bv.WfDiagView.as_view(), name='wf_diag'),
    re_path(r'^(?P<ws_id>[0-9]+)/ws_vdefaults/'
            , bv.WorkspaceVersionDefaultsView.as_view(), name='ws_vdefaults'),
    re_path(r'^vdefaults/'
            , bv.WorkspaceVersionDefaultsView.as_view(), name='vdefaults'),
    re_path(r'^(?P<ws_id>[0-9]+)/jobsum/', bv.jobsum, name='jobsum'),
    re_path(r'^(?P<ws_id>[0-9]+)/job_detail/', bv.job_detail, name='job_detail'),
    re_path(r'^(?P<ws_id>[0-9]+)/jobs/', bv.jobs, name='jobs'),
    re_path(r'^$', bv.index, name='index'),
    re_path(r'^logout/$', av.LogoutView.as_view(), {'next_page': '/account/login/'}, name='mysite_logout'),
    re_path(r'^pwchange/', bv.PasswordChangeView.as_view(success_url='/'), name='pwchange'),
    re_path(r'^publish/(?P<path>.+)', bv.publish),
    re_path(r'^pstatic/(?P<path>.+)', bv.protected_static),
    re_path(r'^api/prot_search/$', ba.prot_search, name='prot_search_api'),
    re_path(r'^api/global_data_prot_search/$', ba.global_data_prot_search, name='global_data_prot_search_api'),
    re_path(r'^api/uniprot/(?P<uniprot>.+)/$', ba.uniprot_lookup, name='uniprot_lookup_api'),
    re_path(r'^api/wsa/(?P<wsa_id>.+)/$', ba.wsa_lookup, name='wsa_lookup_api'),
    re_path(r'^api/list_workspaces/$', ba.list_workspaces, name='list_workspaces_api'),
    re_path(r'^api/list_jobs/$', ba.list_jobs, name='list_jobs_api'),
    re_path(r'^api/ws_molsets/(?P<ws_id>.+)/$', ba.ws_molsets, name='ws_molsets_api'),
    re_path(r'^api/ws_protsets/(?P<ws_id>.+)/$', ba.ws_protsets, name='ws_protsets_api'),
    re_path(r'^api/molset/(?P<ws_id>.+)/(?P<molset_id>.+)/$', ba.molset, name='molset_api'),
    re_path(r'^api/protset/(?P<ws_id>.+)/(?P<protset_id>.+)/$', ba.protset, name='protset_api'),
    re_path(r'^api/search_drugs/(?P<name>.+)/$', ba.search_drugs, name='search_drugs_api'),
    re_path(r'^api/search_wsas/(?P<ws_id>.+)/(?P<name>.+)/$', ba.search_wsas, name='search_wsas_api'),
    re_path(r'^api/fetch_scores/(?P<ws_id>.+)/(?P<job_id>.+)/$', ba.fetch_scores, name='fetch_scores_api'),
    re_path(r'^api/indirect_targets/(?P<target_list>.+)/$', ba.indirect_targets, name='indirect_targets_api'),
    re_path(r'^api/pathway_data/$', ba.pathway_data, name='pathway_data_api'),
    re_path(r'^api/validate_score_json/$', ba.validate_score_json, name='validate_score_json_api'),
    re_path(r'^(?P<ws_id>[0-9]+)/ws_hits/$', bv.WsHitsView.as_view(), name='ws_hits'),
    re_path(r'^hits/$', bv.HitsView.as_view(), name='hits'),
    re_path(r'^selectabilitymodel/(?P<job_id>[0-9]+)/$' , bv.SelectabilityModelView.as_view(), name='selectabilitymodel'),
    re_path(r'^retrospective/$', bv.RetrospectiveView.as_view(), name='retrospective'),
    re_path(r'^suitability/$', bv.SuitabilityView.as_view(), name='suitability'),
    re_path(r'^selectabilityfeatureplot/$', bv.SelectabilityFeaturePlot.as_view(), name='selectabilityfeatureplot'),
    re_path(r'^metricscatterplot/$', bv.MetricScatterPlot.as_view(), name='metricscatterplot'),
    re_path(r'^xws_score_plot/$', bv.XwsScorePlots.as_view(), name='xws_score_plot'),
    re_path(r'^dashboard/$', bv.DashboardView.as_view(), name='dashboard'),
    re_path(r'^(?P<ws_id>[0-9]+)/protset_view/$',
            bv.ProtsetView.as_view(),
            name='protset_view',
            )
]

from django.conf import settings
if False and settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web1/ge/models.py
from django.db import models
from browse.models import AeAccession

class SraRun(models.Model):
    """For BioProject SRAs we know the list of SRX samples beforehand

    We store them in the database for reference as part of meta.
    """

    # Typically SRX###, but can be e.g. ERX or DRX.
    experiment = models.CharField(max_length=64)
    # Typically PRJNA###, but can be e.g. PRJEB or PRJDB
    bioproject = models.CharField(max_length=64, db_index=True)
    # Typically SAMN###, but can be e.g. SAMEA
    biosample = models.CharField(max_length=64)
    # Typically SRR###, but can be e.g. ERR or DRR.
    accession = models.CharField(max_length=64)

    # We pull these out indirectly from the attrs, may not always exist.
    # NOTE: This is the corresponding GEO/GDS ID for the BIOPROJECT/PRJ,
    # not the corresponding AeAccession geoID which will be PRJNA#####.
    geo_id = models.CharField(max_length=64,blank=True,null=True)

    # This will be a list of key-value pairs (potentially duplicate keys).
    attrs_json = models.TextField()
    class Meta:
        unique_together = [('experiment', 'bioproject')]

    def attrs_dict(self):
        import json
        from collections import defaultdict
        data = json.loads(self.attrs_json)
        seen = defaultdict(int)
        out = {}
        # Annoyingly the SRA attrs has repeated keys, so we have to handle that and rename them
        # to be unique.  They will always show up in a consistent order, at least.
        for k, v in data:
            idx = seen[k]
            seen[k] += 1
            if idx > 0:
                k = f'{k}_{idx}'
            out[k] = v
        return out




class GESamples(models.Model):
    """These are ArrayExpress or GEO samples.

    Similar use-case as the SraRun types above.
    Unlike those, however, we have a single entry for all samples for a given experiment.
    
    GEO and AE data has a lot of repeated long text fields, so this helps a lot with compression.
    """
    # We don't tie to a single accession because those are workspace-specific, and we can
    # instead share samples across worskpaces.

    # This corresponds to an AeAccession.geoID
    geoID = models.CharField(max_length=64, primary_key=True)

    # Compressed JSON list of samples, where each sample is a dict of key-value pairs
    attrs_json_gz = models.BinaryField()

    def get_sample_attrs(self):
        import isal.igzip as gzip
        import json
        uncmp = gzip.decompress(self.attrs_json_gz)
        return json.loads(uncmp.decode('utf8'))
    
    @classmethod
    def compress_sample_attrs(cls, attrs):
        if attrs:
            assert(isinstance(attrs[0], dict)), "Samples should be dicts"
        import isal.igzip as gzip
        import json
        byte_data = json.dumps(attrs).encode('utf8')
        cmp = gzip.compress(byte_data)
        return cmp
        

web1/templates/ge/_drugs_by_prot_count.html
{% extends "collapse_section.html" %}
{% block section_label %}
Drugs By Bound Proteins
{% endblock %}
{% block section_body %}
<table class='table'>
	<tr>
		<th>Number of Bound Proteins</th>
		<th>Drugs at this level</th>
	</tr>
	{% for level in drug_prot_levels %}
        <tr>
            <td>
                {{ level.0 }}
            </td>
            <td>
            {{ level.1|length }}:&nbsp;
            {% if level.1|length >= 50 %}
                (Drugs not displayed)
            {% else %}
                {% for id in level.1 %}
                    <a href="{% url 'moldata:annotate' ws.id id %}">{{ id }}</a>&nbsp;
                {% endfor %}
            {% endif %}
            </td>
        </tr>
	{% endfor %}
</table>
{% endblock %}

web1/templates/ge/_significant_protein_stats.html
{% extends "collapse_section.html" %}
{% block section_label %}
Significant Proteins by Tissue Count
{% endblock %}
{% block section_body %}
{% load navtools %}
{% if peo.selected <= 1.0 %}
	evidence level {{ peo.selected }}
{% else %}
	Dataset-specific thresholds
{% endif %}

&nbsp;&nbsp;&nbsp;
<a href="{% url 'ge:kt_tiss' ws.id ts.id %}?thresh={{ peo.selected }}">Compare with KTs</a>
&nbsp;&nbsp;&nbsp;
<a href="{% url 'ge:kt_tiss' ws.id ts.id %}?thresh={{ peo.selected }}&all_drugs=1">Compare with All Drugs</a>
<br>(see {% option_links peo show=section_name %})
<table class='table'>
	<tr>
		<th>Tissues expressing</th>
		<th>Proteins</th>
	</tr>
	{% for level in peo.level_list %}
        <tr>
            <td>
                {{ level.0 }}
            </td>
            <td>
            {{ level.1|length }}:
            {% if level.1|length >= 200 %}
                proteins not displayed
            {% else %}
                {% for prot_id in level.1 %}
                    {% include 'browse/prot_link.html' %}
                {% endfor %}
            {% endif %}
            </td>
        </tr>
	{% endfor %}
</table>
{% endblock %}

web1/templates/ge/ge_overlap.html
{% extends 'base.html' %}

{% block headline %}
	GSM Overlap
{% endblock headline %}
{% block header_left %}
{% endblock header_left %}
{% block header_right %}
{% endblock header_right %}
{% block body %}
{{ table }}
{% endblock body %}

web1/templates/ge/tissues.html
{% extends 'base.html' %}

{% load tissue %}
{% load browse_tags %}

{% block headline %}
    Tissues
{% endblock headline %}
{% block javascript %}
    <script src="/static/lib/Sortable.min.js"></script>
{% endblock javascript %}
{% block header_left %}
    <br><a href="{% url 'ge:ge_overlap' ws.id %}">Sample overlaps</a>
	<br>{{ excluded_link }}
	<br>Sort by:
	{% include "_sortable_clear_button.html" with label="creation" store_name="tissue_order" queryval='id' %}
	{% include "_sortable_clear_button.html" with label="last run" store_name="tissue_order" queryval='run' %}
	{% include "_sortable_clear_button.html" with label="status" store_name="tissue_order" queryval='status' %}
	{% include "_sortable_clear_button.html" with label="tissue set" store_name="tissue_order" queryval='ts' %}
	{% include "_sortable_clear_button.html" with label="accession" store_name="tissue_order" queryval='acc' %}
	{% include "_sortable_clear_button.html" with label="name" store_name="tissue_order" queryval='name' %}
{% endblock header_left %}
{% block header_right %}
    Update Status: {% workflow_status_button 'GeneExpressionData' %}
    <hr>
	<h4>Tissue Sets</h4>
    <form method="post">
    {% csrf_token %}
    <table style='width:auto;' class='table table-condensed'>
    <tr>
        <td></td>
        <td></td>
        <th>update</th>
        <th>redo all</th>
        <th>redo RNASeq</th>
        <th>redo !RNASeq</th>
        <th>update</th>
        <th>redo all</th>
        <th>redo RNASeq</th>
        <th>redo !RNASeq</th>
    </tr>
	{% for ts in tissue_sets %}
    <tr>
        <th>
		<a href="{% url 'ge:tissue_set' ws.id ts.ts_id %}">{{ ts.label }}</a>
        </th>
        <td>
		<a href="{% url 'ge:tissue_stats' ws.id ts.ts_id %}">(stats)</a>
        <a href="{% url 'ge:tissue_corr' ws.id  %}?tissue_set_id={{ ts.ts_id }}"> (corr)</a>
        <a href="{% url 'ge:tissue_set_analysis' ws.id  %}?tissue_set_id={{ ts.ts_id }}"> (sig qc)</a>
        </td>
        {% for t_cnt in ts.labeled_counts %}
        <td>
        {% if t_cnt.1 %}
            <input name="btn_batch_{{ t_cnt.0 }}_{{ ts.ts_id }}{{ t_cnt.3}}"
                type="submit"
                value="{{ t_cnt.1 }} {{ t_cnt.2 }}"
            />
        {% endif %}
        </td>
        {% endfor %}
    </tr>
    {% endfor %}
	<tr>
	<td>
	<a href="{% url 'ge:tissue_set_create' ws.id %}">(Create New)</a>
	</td>
	</tr>
    </table>
    </form>
{% endblock header_right %}
{% block body %}
<table class="table">
<tr>
    <th></th>
    <th>Source</th>
    <th>ID</th>
    <th>Name</th>
    <th>Tissue Set</th>
    <th>Status {{ refresh_link }}</th>
	<th></th>
	<th>{{ result_heading }}</th>
	<th>Quality</th>
</tr>
<tr>
	<td></td>
    <form action="?op=new_tissue" method="post">
        {% csrf_token %}
        <td>{{ tissue_form.source }}<b>{{ tissue_form.source.errors }}</b></td>
        <td>{{ tissue_form.geo_id }}<b>{{ tissue_form.geo_id.errors }}</b></td>
        <td>{{ tissue_form.tissue }}<b>{{ tissue_form.tissue.errors }}</b></td>
        <td>{{ tissue_form.tissue_set }}<b>{{ tissue_form.tissue_set.errors }}</b></td>
        <td>(new)</td>
        <td><input type='submit' value='Fetch'/></td>
    </form>
</tr>
<tr>
	<td></td>
    <form action="?op=import" method="post">
        {% csrf_token %}
        <td>(External)</td>
        <td>{{ tissue_file_form.tsv }}<b>{{ tissue_file_form.tsv.errors }}</b></td>
        <td>(Files from ws/sigprot/*.tsv)</td>
        <td>{{ tissue_file_form.tissue_set }}<b>{{ tissue_file_form.tissue_set.errors }}</b></td>
        <td>(new)</td>
        <td><input type='submit' value='Import'/></td>
    </form>
</tr>
<tbody id="tissue_list_sort" class="list-group">
{% for tissue in tissue_list %}
    <tr data-id="{{ tissue.id }}">
		{% include "_sortable_row_handle.html" %}
        <td>{{ tissue.source_label }}</td>
        <td>{{ tissue.geoID }}</td>
        <td>{{ tissue.name }} ({{ tissue.id }})
		{% if tissue.note %}
			{% note_icon tissue.get_note_text %}
		{% endif %}
            <a href="{% url 'ge:note_tissue' ws.id tissue.id %}" name="pencil">
				{% glyph_icon 'pencil' %}
            </a>
		</td>
		<td>{{ tissue.set_name }}</td>
		{% with tissue.next_action as tna %}
		{% if tna.ok %}
			<td>
		{% else %}
			<td class='warning'>
		{% endif %}
			{{ tna.description }}
			{% if tna.time_info %}
				{% glyph_icon 'time' hover=tna.time_info html=True %}
			{% endif %}
		</td>
        <td>
			{% if tna.primary == 'ABORT' %}
				{% include "ge/tissue_action_button.html" with action_op=tna.phase action_tissue_id=tissue.id action_label=tna.primary %}
			{% else %}
				{% include "ge/_tissue_action_buttons.html" with action_tissue=tissue %}
			{% endif %}
        </td>
		{% endwith %}
        <td>{% with tissue.sig_count_fmt as prot_count %}
            {{ prot_count }}
			{% if tissue.total_proteins %}
            <a href="{% url 'ge:sigprot' ws.id tissue.id %}">
				{% glyph_icon 'stats' %}
            </a>
				{% if tissue.thresh_job_warning %}
					{% info_icon tissue.thresh_job_warning %}
				{% endif %}
			{% endif %}
			{% endwith %}
        </td>
        <td>{% quality_links tissue %}</td>
    </tr>
{% endfor %}
</tbody>
</table>
{% include "_sortable_activator.html" with dom_name="tissue_list_sort" store_name="tissue_order" %}
{% include "_tooltip_activator.html" %}

{% endblock body %}